[package]
name = "rusty-ripper"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
sha2 = "0.10"
md-5 = "0.10" 
hex = "0.4"
csv = "1.3.0"
radix_trie = "0.2"
